"""V1: code motion graphics. Gemini writes a scene against studio_motion; we validate, sandbox-render and encode it."""

from app.services import gemini_client
from app.services.studio.engines import _shared
from app.services.studio.kit import ffmpeg
from app.services.studio.motion import codegen, prompt, render
from app.services.studio.registry import Engine, FieldSpec, RecipeSpec, Stage, StageError

WORDS_PER_SECOND = 2.4
PALETTE_OPTIONS = [{"value": "auto", "label": "Auto (let the AI choose)"}] + [
    {"value": name, "label": label}
    for name, label in (
        ("madrid", "Madrid (navy, gold, white)"), ("midnight", "Midnight (dark blue, cyan)"), ("sunset", "Sunset (purple, orange)"),
        ("neon", "Neon (black, teal, pink)"), ("pitch", "Pitch (green, yellow)"), ("mono", "Mono (black, white)"), ("paper", "Paper (light)"),
    )
]

FIELDS = [
    FieldSpec("brief", "What should the video show?", "textarea", required=True, help="e.g. 'Real Madrid's 15 Champions League titles, big counter, gold on navy'."),
    FieldSpec("data", "Stats / data (optional)", "textarea", help="One fact per line. These are the only numbers the video will use."),
    _shared.aspect_field(),
    FieldSpec("duration", "Length (seconds)", "number", default=15, min=5, max=60),
    FieldSpec("palette", "Colour palette", "select", default="auto", options=PALETTE_OPTIONS),
    FieldSpec("narration", "AI voice-over", "toggle", default=False, help="Gemini writes a short script and a voice reads it."),
    *_shared.tts_fields(),
    *_shared.caption_fields(default_on=True),
]


class MotionEngine(Engine):
    id = "motion"
    label = "Code motion graphics"
    description = "An AI writes a motion-graphics scene as code (counters, bars, reveals) and it is rendered to video. Optional voice-over and captions."
    recipes = [
        RecipeSpec("motion", "Motion graphics", "Animated stat reveals, countdowns and explainers drawn in code.", FIELDS, paid=False, keys=("GEMINI_API_KEY",))
    ]

    def title(self, recipe, params):
        return params["brief"].strip().splitlines()[0][:60]

    def stages(self, recipe, params):
        stages = []
        if params.get("narration"):
            stages += [Stage("Writing narration", _write_narration, "plan"), Stage("Recording voice", _record_voice, "plan")]
        stages += [
            Stage("Designing scene", _design_scene, "plan", weight=3),
            Stage("Rendering frames", _render_frames, "render", weight=6),
            Stage("Finishing video", _finish, "render", weight=2),
        ]
        return stages


def _write_narration(ctx) -> None:
    p = ctx.params
    words = int(max(p["duration"] - 1.5, 3) * WORDS_PER_SECOND)
    data = gemini_client.generate_json(prompt.narration_prompt(p["brief"], p.get("data", ""), p["duration"], words))
    text = str(data.get("narration", "") if isinstance(data, dict) else "").strip()
    if not text:
        raise StageError("Gemini did not return a narration. Retry, or turn the voice-over off.")
    ctx.data["narration"] = text
    ctx.plan["script"] = text
    if isinstance(data, dict) and data.get("title"):
        ctx.data["title"] = str(data["title"])[:80]


def _record_voice(ctx) -> None:
    result = _shared.record_voice(ctx, ctx.data["narration"])
    ctx.plan["scenes"] = [
        {"index": i + 1, "text": s["text"], "visual": "", "duration_s": round(s["end"] - s["start"], 1)} for i, s in enumerate(result.sentences)
    ]


def _design_scene(ctx) -> None:
    p = ctx.params
    w, h = ffmpeg.target_size(p["aspect"])
    duration = float(p["duration"])
    cues = []
    if "tts" in ctx.data:
        spoken = ctx.data["tts"]["duration"]
        duration = max(duration, round(spoken + 0.8, 1))
        cues = [{"start": s["start"], "end": s["end"], "text": s["text"]} for s in ctx.data["tts"]["sentences"]]
    base = prompt.scene_prompt(
        brief=p["brief"], data=p.get("data", ""), aspect=p["aspect"], width=w, height=h, duration=duration,
        palette=p.get("palette", "auto"), cues=cues, assets=[],
    )
    try:
        code = codegen.write_scene(base, width=w, height=h, fps=ffmpeg.FPS, duration=duration, assets={})
    except codegen.SceneCodeError as exc:
        raise StageError(str(exc)) from exc
    ctx.path("scene.py").write_text(code)
    ctx.data["duration"] = duration
    ctx.plan["summary"] = f"{duration:g} s {p['aspect']} motion graphic: {p['brief'].strip()[:140]}"
    ctx.plan["notes"] = "Scene code is generated by AI and sandboxed; the narration (if any) sets the pace."


def _render_frames(ctx) -> None:
    p = ctx.params
    w, h = ffmpeg.target_size(p["aspect"])
    duration = ctx.data["duration"]
    try:
        render.render_scene(
            ctx.path("scene.py").read_text(), ctx.path("motion.mp4"), width=w, height=h, fps=ffmpeg.FPS, duration=duration,
            timeout=min(max(120, duration * 6), ctx.remaining()), progress=ctx.progress,
        )
    except render.MotionRenderError as exc:
        raise StageError(f"The scene failed to render: {exc}") from exc


def _finish(ctx) -> None:
    p = ctx.params
    tts_data = ctx.data.get("tts")
    audio = ctx.asset("narration") if tts_data else None
    _shared.compose_final(
        ctx, ctx.path("motion.mp4"), seconds=ctx.data["duration"], audio=audio, sentences=tts_data["sentences"] if tts_data else None,
        captions_on=bool(p.get("subtitles")) and bool(tts_data), style=p.get("caption_style", "bold-pop"), position=p.get("subtitle_position", "bottom"),
    )


ENGINE = MotionEngine()
